### ISSUE TITLE
Cannot create new wiki accounts

### ISSUE THREAD

**Issue by TylerJuch** [FAForever/website#119]
Currently, you cannot create a new account at https://wiki.faforever.com. Not sure if Wiki site issues belong here, since I don't think any code related to that lives here, but I wanted to report it somewhere.

```
[a16e7115] /index.php?title=Special:UserLogin&action=submitlogin&type=signup&returnto=Main+Page MWException from line 291 of /usr/share/nginx/html/includes/mail/UserMailer.php: PEAR mail package is not installed
Backtrace:
#0 /usr/share/nginx/html/includes/User.php(4260): UserMailer::send(MailAddress, MailAddress, string, string, array)
#1 /usr/share/nginx/html/includes/User.php(4233): User->sendMail(string, string)
#2 /usr/share/nginx/html/includes/specials/SpecialUserlogin.php(437): User->sendConfirmationMail()
#3 /usr/share/nginx/html/includes/specials/SpecialUserlogin.php(333): LoginForm->addNewAccount()
#4 /usr/share/nginx/html/includes/specialpage/SpecialPage.php(384): LoginForm->execute(NULL)
#5 /usr/share/nginx/html/includes/specialpage/SpecialPageFactory.php(553): SpecialPage->run(NULL)
#6 /usr/share/nginx/html/includes/MediaWiki.php(281): SpecialPageFactory::executePath(Title, RequestContext)
#7 /usr/share/nginx/html/includes/MediaWiki.php(714): MediaWiki->performRequest()
#8 /usr/share/nginx/html/includes/MediaWiki.php(508): MediaWiki->main()
#9 /usr/share/nginx/html/index.php(41): MediaWiki->run()
#10 {main}
```

**Comment by Raistlfiren** [comment]
@TylerJuch This is for the website, not the wikipedia. I have put your issue in the correct repository.
