### ISSUE TITLE
Website crashes on fetching clan data

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/website#234]
```
There was an error retrieving the clan index page table: null

Trace: {
  errors: [
    'InvalidValueException: Invalid value: Combination of pagination, sorting over relationship and filtering over toMany relationships unsupported'
  ]
}
    at Request._callback (/code/routes/views/clans/get/index.js:52:29)
    at Request.self.callback (/code/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/code/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/code/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

**Comment by 1-alex98** [comment]
Also the arrows for sorting the table can not be displayed
