### ISSUE TITLE
Frequent website crash

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/website#95]
For the last two weeks or so, the website has been crashing every couple days.

Please investigate and fix.

I will post logs if I find some.

**Comment by duk3luk3** [comment]
Caught the logs:

```
website_1                  | <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
website_1                  | ^
website_1                  | 
website_1                  | SyntaxError: Unexpected token < in JSON at position 0
website_1                  |     at JSON.parse (<anonymous>)
website_1                  |     at Request._callback (/code/express.js:141:21)
website_1                  |     at Request.self.callback (/code/node_modules/request/request.js:186:22)
website_1                  |     at emitTwo (events.js:106:13)
website_1                  |     at Request.emit (events.js:191:7)
website_1                  |     at Request.<anonymous> (/code/node_modules/request/request.js:1081:10)
website_1                  |     at emitOne (events.js:96:13)
website_1                  |     at Request.emit (events.js:188:7)
website_1                  |     at IncomingMessage.<anonymous> (/code/node_modules/request/request.js:1001:12)
website_1                  |     at IncomingMessage.g (events.js:292:16)
website_1                  |     at emitNone (events.js:91:20)
website_1                  |     at IncomingMessage.emit (events.js:185:7)
website_1                  |     at endReadableNT (_stream_readable.js:974:12)
website_1                  |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
website_1                  |     at process._tickCallback (internal/process/next_tick.js:98:9)
website_1                  | 
website_1                  | npm info lifecycle website@0.0.0~start: Failed to exec start script
website_1                  | npm ERR! Linux 3.13.0-76-generic
website_1                  | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
website_1                  | npm ERR! node v7.2.1
website_1                  | npm ERR! npm  v3.10.10
website_1                  | npm ERR! code ELIFECYCLE
website_1                  | npm ERR! website@0.0.0 start: `node express.js`
website_1                  | npm ERR! Exit status 1
website_1                  | npm ERR! 
website_1                  | npm ERR! Failed at the website@0.0.0 start script 'node express.js'.
website_1                  | npm ERR! Make sure you have the latest version of node.js and npm installed.
website_1                  | npm ERR! If you do, this is most likely a problem with the website package,
website_1                  | npm ERR! not with npm itself.
website_1                  | npm ERR! Tell the author that this fails on your system:
website_1                  | npm ERR!     node express.js
website_1                  | npm ERR! You can get information on how to open an issue for this project with:
website_1                  | npm ERR!     npm bugs website
website_1                  | npm ERR! Or if that isn't available, you can get their info via:
website_1                  | npm ERR!     npm owner ls website
website_1                  | npm ERR! There is likely additional logging output above.
website_1                  | 
website_1                  | npm ERR! Please include the following file with any support request:
website_1                  | npm ERR!     /code/npm-debug.log
```

**Comment by Raistlfiren** [comment]
@duk3luk3 - Thank you so much for the follow up email. I have added a check to the oauth verification, and I have pushed it to `develop` and `master`. It is tagged in v1.1.1.8.

**Comment by Raistlfiren** [comment]
Is this still a problem? It seems as though this should be closed.
